version: "3.2"
services:
  coldfusion:
    image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
    environment: 
      acceptEULA: "YES"
      password: "myPassword"
      TZ: "UTC"
      installModules: "mysql"
    ports:
      - 8500:8500
    volumes:
      - ${PWD}/app:/app   
      - ${PWD}/data/:/data
      - ${PWD}/drivers/mysql-connector-java-8.0.21.jar:/opt/ColdFusion/cfusion/lib/mysql-connecor-java-8.0.21.jar
    networks:
      - internal

  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "myPassword"
      TZ: "UTC"
    volumes:
      - ${PWD}/database:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal

networks:
  internal: