version: "3"
services:
  coldfusion:
    image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
    environment: 
      - acceptEULA=YES
      - PUID=1000
      - PGID=1000
      - password=myPassword    
    ports:
      - 8500:8500     # Main http port
      - 8581:8581     # Web socket port
      - 5005:5005     # Debugger port
    volumes:
      - ${PWD}/app:/app
      - ${PWD}/logs/:/opt/coldfusion/cfusion/logs/
    