version: "3.2"
services:
  coldfusion:
    image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
    environment: 
      acceptEULA: "YES"
      password: "myPassword"
      installModules: "caching"
    ports:
      - 8500:8500
    volumes:
      - ${PWD}/app:/app
      - ${PWD}/logs/:/opt/ColdFusion/cfusion/logs/   #Prior to CF2021, path is /opt/coldfusion/cfusion/logs 
